### ISSUE TITLE
Bookshelf variants drop nothing when broken [1.21]

### ISSUE THREAD

**Issue by ColdStoneSys** [pnk2u/More-Chiseled-Bookshelf-Variants#5]
When the blocks are broken no item drops

https://youtu.be/QH--PPWKSMQ

**Comment by pnk2u** [comment]
Hi, thanks for reporting this issue and even supplying a video, I appreciate it a lot.
The issue should be fixed in version 1.6.1. Let me know if there's anything else and thanks again. (:

**Comment by ColdStoneSys** [comment]
Can confirm that it is fixed
